"""update transaction schema

Revision ID: 4fe421f9ceac
Revises: 4e091d7f0a91
Create Date: 2026-04-15 18:17:56.905071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe421f9ceac'
down_revision: Union[str, Sequence[str], None] = '4e091d7f0a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_type', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('device_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('model_version', sa.String(), nullable=True))
    op.add_column('users', sa.Column('known_ips', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('known_devices', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'known_devices')
    op.drop_column('users', 'known_ips')
    op.drop_column('transactions', 'model_version')
    op.drop_column('transactions', 'device_id')
    op.drop_column('transactions', 'ip_address')
    op.drop_column('transactions', 'receiver_id')
    op.drop_column('transactions', 'transaction_type')
    # ### end Alembic commands ###
