"""remove security question fields

Revision ID: 819fc9c17069
Revises: 283dbbe44225
Create Date: 2026-04-16 15:59:51.755005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819fc9c17069'
down_revision: Union[str, Sequence[str], None] = '283dbbe44225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'security_question')
    op.drop_column('users', 'security_answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('security_answer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('security_question', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
