"""init clean

Revision ID: ae3fadba002a
Revises: 
Create Date: 2026-04-18 09:25:54.540262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae3fadba002a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('account_balance', sa.Float(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_login_attempt_reset', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('unblock_otp_hash', sa.String(), nullable=True),
    sa.Column('unblock_otp_expiry', sa.DateTime(), nullable=True),
    sa.Column('unblock_otp_used', sa.Boolean(), nullable=False),
    sa.Column('unblock_otp_attempts', sa.Integer(), nullable=False),
    sa.Column('last_unblock_otp_request', sa.DateTime(), nullable=True),
    sa.Column('otp_hash', sa.String(), nullable=True),
    sa.Column('otp_expiry', sa.DateTime(), nullable=True),
    sa.Column('otp_attempts', sa.Integer(), nullable=False),
    sa.Column('last_otp_request', sa.DateTime(), nullable=True),
    sa.Column('known_ips', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('known_devices', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('phone', name='uq_user_phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fraud_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('fraud_score', sa.Float(), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_logs_created_at'), 'fraud_logs', ['created_at'], unique=False)
    op.create_index('ix_fraud_logs_user_created', 'fraud_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_fraud_logs_user_id'), 'fraud_logs', ['user_id'], unique=False)
    op.create_table('otp_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('otp_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_logs_user_id'), 'otp_logs', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('account_balance', sa.Float(), nullable=False),
    sa.Column('transaction_duration', sa.Float(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('login_attempts', sa.Integer(), nullable=True),
    sa.Column('fraud_score', sa.Float(), nullable=False),
    sa.Column('ml_probability', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('is_fraud', sa.Boolean(), nullable=False),
    sa.Column('reasons', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('receiver_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='PENDING', nullable=False),
    sa.Column('auto_complete_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('refund_transaction_id', sa.UUID(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','DELAYED','COMPLETED','REPORTED','REVERSED','CANCELLED')", name='ck_transaction_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_transactions_public_id'), 'transactions', ['public_id'], unique=True)
    op.create_index('ix_transactions_status_auto_complete', 'transactions', ['status', 'auto_complete_at'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_index('ix_transactions_user_status', 'transactions', ['user_id', 'status'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entry_type IN ('debit','credit')", name='ck_ledger_entry_type'),
    sa.CheckConstraint('amount > 0', name='ck_ledger_amount_positive'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_transaction_id'), 'ledger_entries', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_user_id'), 'ledger_entries', ['user_id'], unique=False)
    op.create_index('ix_ledger_transaction', 'ledger_entries', ['transaction_id'], unique=False)
    op.create_index('ix_ledger_user_created', 'ledger_entries', ['user_id', 'created_at'], unique=False)
    op.create_table('transaction_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=True),
    sa.Column('otp_expiry', sa.DateTime(), nullable=True),
    sa.Column('otp_used', sa.Boolean(), nullable=False),
    sa.Column('otp_attempts', sa.Integer(), nullable=False),
    sa.Column('last_otp_sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', name='uq_report_transaction_id')
    )
    op.create_index(op.f('ix_transaction_reports_transaction_id'), 'transaction_reports', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_transaction_reports_user_id'), 'transaction_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_reports_user_id'), table_name='transaction_reports')
    op.drop_index(op.f('ix_transaction_reports_transaction_id'), table_name='transaction_reports')
    op.drop_table('transaction_reports')
    op.drop_index('ix_ledger_user_created', table_name='ledger_entries')
    op.drop_index('ix_ledger_transaction', table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_user_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_transaction_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('ix_transactions_user_status', table_name='transactions')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index('ix_transactions_status_auto_complete', table_name='transactions')
    op.drop_index(op.f('ix_transactions_public_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_otp_logs_user_id'), table_name='otp_logs')
    op.drop_table('otp_logs')
    op.drop_index(op.f('ix_fraud_logs_user_id'), table_name='fraud_logs')
    op.drop_index('ix_fraud_logs_user_created', table_name='fraud_logs')
    op.drop_index(op.f('ix_fraud_logs_created_at'), table_name='fraud_logs')
    op.drop_table('fraud_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
